version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TripTrekStack"
s3_bucket = "wits-sam-deployments"
s3_prefix = "triptrek"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
resolve_s3 = false

[default.build.parameters]
cached = true
parallel = true
use_container = false