AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda + API Gateway using SAM

Parameters:
  ImageUploadBucket:
    Type: String
    Description: S3 bucket for uploaded location images
    Default: triptrek-location-images

Resources:

  TripTrekTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TripTrek
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  TripTrekAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: TripTrekAPI
      CorsConfiguration:
        AllowMethods:
          - GET
          - POST
          - PATCH
          - DELETE
        AllowOrigins:
          - "*"
        AllowHeaders:
          - "*"

  LocationImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ImageUploadBucket
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - "*"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  createTrip:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createTrip
      Handler: index.handler
      Runtime: nodejs22.x 
      CodeUri: create/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /createTrip
            Method: POST
            ApiId: !Ref TripTrekAPI

  getTripList:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getTripList
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: read/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /getTripList
            Method: GET
            ApiId: !Ref TripTrekAPI
  
  updateTrip:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: updateTrip
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: update/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /updateTrip
            Method: PATCH
            ApiId: !Ref TripTrekAPI

  deleteTrip:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: deleteTrip
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: delete/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: TripTrek
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /deleteTrip
            Method: DELETE
            ApiId: !Ref TripTrekAPI
  
  imageUploader:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: imageUploader
      Handler: index.handler
      Runtime: nodejs22.x
      CodeUri: images/
      Environment:
        Variables:
          LOCATION_IMAGES_BUCKET: !Ref ImageUploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref ImageUploadBucket
      Events:
        ApiForMyApp:
          Type: HttpApi
          Properties:
            Path: /generateUploadUrl
            Method: POST
            ApiId: !Ref TripTrekAPI

Outputs:
  ApiUrl:
    Description: "HTTP API endpoint base URL"
    Value: !Sub "https://${TripTrekAPI}.execute-api.${AWS::Region}.amazonaws.com"
  LocationImagesBucketName:
    Description: "S3 Image Bucket Name"
    Value: !Ref LocationImagesBucket