import os

# Create the .github/workflows directory if it doesn't exist
os.makedirs(".github/workflows", exist_ok=True)

# Define the updated GitHub Actions workflow with Node.js version 20 setup using nvm
updated_workflow = """name: CI/CD Pipeline

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main

jobs:
  test-frontend:
    name: Run Frontend Unit Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ../frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js 20 using nvm
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
          nvm install 20
          nvm use 20
          node -v
          npm -v

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test -- --coverage

  deploy-backend:
    name: Deploy Backend (SAM)
    runs-on: ubuntu-latest
    needs: test-frontend
    if: github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ../backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM application
        run: sam build

      - name: Deploy SAM application
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name TripTrekStack --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
"""

# Save the updated workflow to a file
with open(".github/workflows/deploy.yml", "w") as f:
    f.write(updated_workflow)

print("Updated deploy.yml file has been saved with Node.js 20 setup using nvm.")

